### ISSUE TITLE
[Actividad RISC-V] Pokemons muertos

### ISSUE THREAD

**Issue by Aessha** [IIC2343/Syllabus-2024-2#105]
a la hora de correr el simulador termina cuando squirtel sube a nivel 10, sin embargo los pokemons estuvieron peleando muertos hasta conseguir esto, entiendo que la curacion de los pokemons se maneja en el utils no?

**Comment by Aessha** [comment]
interprete mal el output asdlkajld perdon

**Comment by sufigueroa** [comment]
No están muertos, solo descansando 😧
