### ISSUE TITLE
[Proyecto | Etapa 2] Dudas sobre labels en assembler

### ISSUE THREAD

**Issue by fgarl** [IIC2343/Syllabus-2024-2#107]
Tengo dos dudas, la primera es si en la seccion data puede aparecer mas de una vez la misma label, por ejemplo
```
DATA:
aaa 5
aaa 3
```
Si es posible que aparezca, que valor tiene aaa, 5 o 3, y a que direccion apunta, 0 o 1?

La otra es si las labels pueden tener parentesis en sus nombres, por ejemplo:
```
DATA:
(a)   6
```

**Comment by Javipipi** [comment]
Hola!, no ocurrirá ninguno de los casos que dices :).

**Comment by fgarl** [comment]
Yap, muchas gracias!
