### ISSUE TITLE
Sala i1 alumnos PIANE

### ISSUE THREAD

**Issue by bozzimuc** [IIC2343/Syllabus-2024-2#17]
Buenas tardes
Dentro de las adecuaciones para los alumnos del programa PIANE, se solicita que podamos rendir las interrogaciones escritas en una sala separada al resto de los alumnos, y con un 50% de tiempo adicional.
En la tabla que enviaron por Canvas, se me asignó la sala A1, junto a varios otros compañeros los cuales asumo no son todos del PIANE.
¿Se nos entregará una sala aparte mañana?
Muchas gracias

**Comment by Geeermy** [comment]
¡Hola!

Les enviaremos pronto un correo a quienes se encuentran en la lista PIANE, pero desde ya les confirmo que ustedes deben rendir la prueba en la sala **B11**.

¡Saludos!

**Comment by bozzimuc** [comment]
Vale, muchas gracias!
