### ISSUE TITLE
[Proyecto | Etapa 3] Existe el enunciado?

### ISSUE THREAD

**Issue by 3rdPix** [IIC2343/Syllabus-2024-2#54]
Hola!

Me preguntaba si ya existía el enunciado para la etapa 3 del proyecto... y de existir, si podían subirlo por favor🦎

**Comment by frvalenzuela** [comment]
Hola @3rdPix !

Todavía no estamos a tiempo de subir el enunciado de la etapa 3. En cuanto este listo se subirá.

Saludos!
