### ISSUE TITLE
[Actividad RISC-V] Error Runtime

### ISSUE THREAD

**Issue by Constanza-Vilches** [IIC2343/Syllabus-2024-2#80]
Hola, buenos dias, estaba corriendo el codigo de la actividad y me aparece que tengo un error en la linea 194 del tipo Runtime exception at 0x00400284: Upper bound of range cannot be negative (syscall 42). Desconozco los tipos de errores que pueden tirar risc v, por tanto quisiera darme una idea del porque me podria estar saltando este error o de que se trata.
(En otra issue salia que era sobre actualizar el archivo a la ultima version, pero no se si sea por eso y tampoco se como hacerlo)

**Comment by frvalenzuela** [comment]
Hola @Constanza-Vilches !

Esto indica que el syscall 42 no puede ser negativo. Este es que se ocupa para llamado de subrutina de números aleatorios. Seguramente el error estas dando un número menor a cero como parametro.

Saludos

**Comment by Constanza-Vilches** [comment]
El error no me da en el llamado de una subrutina. Me esta dando al momento de tratar de leer los elementos en memoria del pokemon, estoy haciendo un lw t0, 40(direccion memoria pokemon). Tengo entendido que al hacer esto deberia guardarse en t0 lo que este en el offset 40 de la direccion entregada, no se que podria estar mal en mi codigo. De hecho me aseguro de guardar las direcciones de memoria, para que no puedan sobre escribirse... tambien antes de ese error hago otros lw y no salta ningun error...

**Comment by Constanza-Vilches** [comment]
Acabo de ver bien el flujo del programa desde el execute y me marca el problema en una ecall de print_string - print_number, pero todo eso es del codigo base, que podria hacer? Sera que estoy re escribiendo algun registro esencial para esas ecalls?

**Comment by Constanza-Vilches** [comment]
@frvalenzuela

**Comment by frvalenzuela** [comment]
Hola @Constanza-Vilches !

Te recomiendo asegurarte que a0 sea la direccion memoria pokemon . Seguramente el a0 no es una dirección de memoria de pokemon.

Saludos!
