### ISSUE TITLE
[Actividad RISC-V] Error Runtime

### ISSUE THREAD

**Issue by Aessha** [IIC2343/Syllabus-2024-2#84]
Hola, buenos dias, ahora corriendo el codigo me salta este error que pertenece al archivo pokemon_utils.asm "Runtime exception at 0x0040008c: Load address not aligned to word boundary 0x10010143" la linea en cuestion es esta "lw t0, 0(a0)" y entiendo que tiene que ver con el manejo de a0 y su alineacion, pero no logro identificar de donde proviene el error, porque entiendo que antes de llamar a esta subrita se deberia inicializar bien a0, ya que no soy yo el que la esta llamando.

**Comment by frvalenzuela** [comment]
Hola @Aessha !

No es un problema de utils, podría ser o bien a0 ya no es una dirección, o el valor que retorna ya no es una dirección. Pero puedo asegurar que no es problema de lo definido en utils.

Saludos
